/**
 * Trinity Inventory Apps — Granular Permissions System
 *
 * 85+ permissions dengan 3-tier model:
 * 1. ROLE_DEFAULT_PERMISSIONS — fallback permissions per role
 * 2. ROLE_RESTRICTIONS — hard-blocked permissions per role
 * 3. MANDATORY_PERMISSIONS — always-granted regardless of DB config
 *
 * @see SECURITY_AND_RBAC_MATRIX.md §3.2–§3.5
 */
import { UserRole } from '../../generated/prisma/client';

// ─── Permission Keys ─────────────────────────────────────────────

export const PERMISSIONS = {
  // Dashboard & Reports
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  REPORTS_VIEW: 'REPORTS_VIEW',
  DATA_EXPORT: 'DATA_EXPORT',
  SYSTEM_AUDIT_LOG: 'SYSTEM_AUDIT_LOG',

  // Procurement (Permintaan Baru)
  REQUESTS_VIEW_OWN: 'REQUESTS_VIEW_OWN',
  REQUESTS_VIEW_ALL: 'REQUESTS_VIEW_ALL',
  REQUESTS_CREATE: 'REQUESTS_CREATE',
  REQUESTS_CREATE_URGENT: 'REQUESTS_CREATE_URGENT',
  REQUESTS_APPROVE_LOGISTIC: 'REQUESTS_APPROVE_LOGISTIC',
  REQUESTS_APPROVE_PURCHASE: 'REQUESTS_APPROVE_PURCHASE',
  REQUESTS_APPROVE_FINAL: 'REQUESTS_APPROVE_FINAL',
  REQUESTS_CANCEL_OWN: 'REQUESTS_CANCEL_OWN',
  REQUESTS_DELETE: 'REQUESTS_DELETE',

  // Loan Management (Peminjaman)
  LOAN_REQUESTS_VIEW_OWN: 'LOAN_REQUESTS_VIEW_OWN',
  LOAN_REQUESTS_VIEW_ALL: 'LOAN_REQUESTS_VIEW_ALL',
  LOAN_REQUESTS_CREATE: 'LOAN_REQUESTS_CREATE',
  LOAN_REQUESTS_APPROVE: 'LOAN_REQUESTS_APPROVE',
  LOAN_REQUESTS_RETURN: 'LOAN_REQUESTS_RETURN',

  // Asset Management
  ASSETS_VIEW: 'ASSETS_VIEW',
  ASSETS_VIEW_DIVISION: 'ASSETS_VIEW_DIVISION',
  ASSETS_VIEW_PRICE: 'ASSETS_VIEW_PRICE',
  ASSETS_CREATE: 'ASSETS_CREATE',
  ASSETS_EDIT: 'ASSETS_EDIT',
  ASSETS_DELETE: 'ASSETS_DELETE',
  ASSETS_HANDOVER: 'ASSETS_HANDOVER',
  HANDOVERS_VIEW: 'HANDOVERS_VIEW',
  ASSETS_REPAIR_REPORT: 'ASSETS_REPAIR_REPORT',
  ASSETS_REPAIR_MANAGE: 'ASSETS_REPAIR_MANAGE',

  // Field Operations (Instalasi, Maintenance, Dismantle)
  ASSETS_INSTALL: 'ASSETS_INSTALL',
  INSTALLATIONS_VIEW: 'INSTALLATIONS_VIEW',
  ASSETS_DISMANTLE: 'ASSETS_DISMANTLE',
  DISMANTLES_VIEW: 'DISMANTLES_VIEW',
  MAINTENANCES_CREATE: 'MAINTENANCES_CREATE',
  MAINTENANCES_VIEW: 'MAINTENANCES_VIEW',

  // Stock & Inventory
  STOCK_VIEW: 'STOCK_VIEW',
  STOCK_MANAGE: 'STOCK_MANAGE',

  // Customer Management
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_CREATE: 'CUSTOMERS_CREATE',
  CUSTOMERS_EDIT: 'CUSTOMERS_EDIT',
  CUSTOMERS_DELETE: 'CUSTOMERS_DELETE',

  // User & Division Management
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',
  USERS_RESET_PASSWORD: 'USERS_RESET_PASSWORD',
  USERS_MANAGE_PERMISSIONS: 'USERS_MANAGE_PERMISSIONS',
  DIVISIONS_MANAGE: 'DIVISIONS_MANAGE',
  ACCOUNT_MANAGE: 'ACCOUNT_MANAGE',

  // Categories & Projects
  CATEGORIES_VIEW: 'CATEGORIES_VIEW',
  CATEGORIES_MANAGE: 'CATEGORIES_MANAGE',
  PROJECTS_VIEW: 'PROJECTS_VIEW',
  PROJECTS_CREATE: 'PROJECTS_CREATE',
  PROJECTS_EDIT: 'PROJECTS_EDIT',
  PROJECTS_APPROVE: 'PROJECTS_APPROVE',
  PROJECTS_MANAGE_TEAM: 'PROJECTS_MANAGE_TEAM',
  PROJECTS_MANAGE_TASKS: 'PROJECTS_MANAGE_TASKS',

  // Returns
  RETURNS_VIEW: 'RETURNS_VIEW',
  RETURNS_CREATE: 'RETURNS_CREATE',
  RETURNS_APPROVE: 'RETURNS_APPROVE',

  // Imports
  DATA_IMPORT: 'DATA_IMPORT',

  // Purchases & Depreciation
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_CREATE: 'PURCHASES_CREATE',
  PURCHASES_EDIT: 'PURCHASES_EDIT',
  PURCHASES_DELETE: 'PURCHASES_DELETE',
  DEPRECIATION_VIEW: 'DEPRECIATION_VIEW',
  DEPRECIATION_CREATE: 'DEPRECIATION_CREATE',
  DEPRECIATION_EDIT: 'DEPRECIATION_EDIT',
  DEPRECIATION_DELETE: 'DEPRECIATION_DELETE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ─── Role Default Permissions (Tier 1 — Fallback) ────────────────

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPERADMIN]: [], // bypass — checked before defaults

  [UserRole.ADMIN_LOGISTIK]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.DATA_IMPORT,
    PERMISSIONS.REQUESTS_VIEW_OWN,
    PERMISSIONS.REQUESTS_VIEW_ALL,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REQUESTS_CREATE_URGENT,
    PERMISSIONS.REQUESTS_APPROVE_LOGISTIC,
    PERMISSIONS.REQUESTS_CANCEL_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_ALL,
    PERMISSIONS.LOAN_REQUESTS_CREATE,
    PERMISSIONS.LOAN_REQUESTS_APPROVE,
    PERMISSIONS.LOAN_REQUESTS_RETURN,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_VIEW_DIVISION,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_HANDOVER,
    PERMISSIONS.HANDOVERS_VIEW,
    PERMISSIONS.ASSETS_REPAIR_REPORT,
    PERMISSIONS.ASSETS_REPAIR_MANAGE,
    PERMISSIONS.ASSETS_INSTALL,
    PERMISSIONS.INSTALLATIONS_VIEW,
    PERMISSIONS.ASSETS_DISMANTLE,
    PERMISSIONS.DISMANTLES_VIEW,
    PERMISSIONS.MAINTENANCES_CREATE,
    PERMISSIONS.MAINTENANCES_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_APPROVE,
    PERMISSIONS.PROJECTS_MANAGE_TEAM,
    PERMISSIONS.PROJECTS_MANAGE_TASKS,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_APPROVE,
    PERMISSIONS.PURCHASES_VIEW,
  ],

  [UserRole.ADMIN_PURCHASE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.REQUESTS_VIEW_OWN,
    PERMISSIONS.REQUESTS_VIEW_ALL,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REQUESTS_CREATE_URGENT,
    PERMISSIONS.REQUESTS_APPROVE_PURCHASE,
    PERMISSIONS.REQUESTS_CANCEL_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_OWN,
    PERMISSIONS.LOAN_REQUESTS_CREATE,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_VIEW_PRICE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_EDIT,
    PERMISSIONS.PURCHASES_DELETE,
    PERMISSIONS.DEPRECIATION_VIEW,
    PERMISSIONS.DEPRECIATION_CREATE,
    PERMISSIONS.DEPRECIATION_EDIT,
    PERMISSIONS.DEPRECIATION_DELETE,
  ],

  [UserRole.LEADER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.REQUESTS_VIEW_OWN,
    PERMISSIONS.REQUESTS_VIEW_ALL,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REQUESTS_CREATE_URGENT,
    PERMISSIONS.REQUESTS_CANCEL_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_ALL,
    PERMISSIONS.LOAN_REQUESTS_CREATE,
    PERMISSIONS.LOAN_REQUESTS_APPROVE,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_VIEW_DIVISION,
    PERMISSIONS.HANDOVERS_VIEW,
    PERMISSIONS.ASSETS_REPAIR_REPORT,
    PERMISSIONS.ASSETS_INSTALL,
    PERMISSIONS.INSTALLATIONS_VIEW,
    PERMISSIONS.ASSETS_DISMANTLE,
    PERMISSIONS.DISMANTLES_VIEW,
    PERMISSIONS.MAINTENANCES_CREATE,
    PERMISSIONS.MAINTENANCES_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_MANAGE_TEAM,
    PERMISSIONS.PROJECTS_MANAGE_TASKS,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_CREATE,
  ],

  [UserRole.STAFF]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REQUESTS_VIEW_OWN,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REQUESTS_CANCEL_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_OWN,
    PERMISSIONS.LOAN_REQUESTS_CREATE,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.HANDOVERS_VIEW,
    PERMISSIONS.ASSETS_REPAIR_REPORT,
    PERMISSIONS.ASSETS_INSTALL,
    PERMISSIONS.INSTALLATIONS_VIEW,
    PERMISSIONS.ASSETS_DISMANTLE,
    PERMISSIONS.DISMANTLES_VIEW,
    PERMISSIONS.MAINTENANCES_CREATE,
    PERMISSIONS.MAINTENANCES_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_CREATE,
  ],
};

// ─── Role Restrictions (Tier 2 — Hard Blocks) ────────────────────

export const ROLE_RESTRICTIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPERADMIN]: [], // no restrictions

  [UserRole.ADMIN_LOGISTIK]: [
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.SYSTEM_AUDIT_LOG,
    PERMISSIONS.DIVISIONS_MANAGE,
  ],

  [UserRole.ADMIN_PURCHASE]: [
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.SYSTEM_AUDIT_LOG,
    PERMISSIONS.DIVISIONS_MANAGE,
  ],

  [UserRole.LEADER]: [
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.REQUESTS_DELETE,
    PERMISSIONS.SYSTEM_AUDIT_LOG,
    PERMISSIONS.DIVISIONS_MANAGE,
  ],

  [UserRole.STAFF]: [
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.ASSETS_VIEW_PRICE,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.REQUESTS_DELETE,
    PERMISSIONS.SYSTEM_AUDIT_LOG,
    PERMISSIONS.DIVISIONS_MANAGE,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.REQUESTS_APPROVE_FINAL,
  ],
};

// ─── Mandatory Permissions (Tier 3 — Always Granted) ─────────────

export const MANDATORY_PERMISSIONS: Record<string, Permission[]> = {
  ALL: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ACCOUNT_MANAGE],

  [UserRole.STAFF]: [
    PERMISSIONS.REQUESTS_VIEW_OWN,
    PERMISSIONS.REQUESTS_CREATE,
    PERMISSIONS.REQUESTS_CANCEL_OWN,
    PERMISSIONS.LOAN_REQUESTS_VIEW_OWN,
    PERMISSIONS.LOAN_REQUESTS_CREATE,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.HANDOVERS_VIEW,
    PERMISSIONS.ASSETS_REPAIR_REPORT,
  ],
};

// ─── Permission Check Logic ──────────────────────────────────────

/**
 * 3-tier permission check sesuai SECURITY_AND_RBAC_MATRIX.md §3.2:
 *
 * 1. SUPER_ADMIN → GRANT (bypass)
 * 2. ROLE_RESTRICTIONS → DENY (hard block)
 * 3. MANDATORY_PERMISSIONS → GRANT (auto-inject)
 * 4. userPermissions[] (dari DB) → GRANT
 * 5. ROLE_DEFAULT_PERMISSIONS → GRANT (fallback)
 * 6. Else → DENY
 */
export function hasPermission(
  role: UserRole,
  userPermissions: string[],
  requiredPermission: Permission,
): boolean {
  // 1. SUPER_ADMIN bypass
  if (role === UserRole.SUPERADMIN) return true;

  // 2. Role restrictions — hard block
  if (ROLE_RESTRICTIONS[role]?.includes(requiredPermission)) return false;

  // 3. Mandatory permissions — always granted
  if (MANDATORY_PERMISSIONS['ALL']?.includes(requiredPermission)) return true;
  if (MANDATORY_PERMISSIONS[role]?.includes(requiredPermission)) return true;

  // 4. User-specific permissions from DB
  if (userPermissions.includes(requiredPermission)) return true;

  // 5. Role default permissions — fallback
  if (ROLE_DEFAULT_PERMISSIONS[role]?.includes(requiredPermission)) return true;

  // 6. Deny
  return false;
}
