/**
 * Frontend permission constants — mirrors backend PERMISSIONS keys.
 * Used by usePermissions() hook for UI-level access control.
 */
export const P = {
  // Dashboard & Reports
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  REPORTS_VIEW: 'REPORTS_VIEW',
  DATA_EXPORT: 'DATA_EXPORT',

  // Procurement (Permintaan Baru)
  REQUESTS_VIEW_OWN: 'REQUESTS_VIEW_OWN',
  REQUESTS_VIEW_ALL: 'REQUESTS_VIEW_ALL',
  REQUESTS_CREATE: 'REQUESTS_CREATE',
  REQUESTS_APPROVE_LOGISTIC: 'REQUESTS_APPROVE_LOGISTIC',
  REQUESTS_APPROVE_PURCHASE: 'REQUESTS_APPROVE_PURCHASE',
  REQUESTS_APPROVE_FINAL: 'REQUESTS_APPROVE_FINAL',
  REQUESTS_CANCEL_OWN: 'REQUESTS_CANCEL_OWN',

  // Loan Management
  LOAN_REQUESTS_VIEW_OWN: 'LOAN_REQUESTS_VIEW_OWN',
  LOAN_REQUESTS_VIEW_ALL: 'LOAN_REQUESTS_VIEW_ALL',
  LOAN_REQUESTS_CREATE: 'LOAN_REQUESTS_CREATE',
  LOAN_REQUESTS_APPROVE: 'LOAN_REQUESTS_APPROVE',

  // Asset Management
  ASSETS_VIEW: 'ASSETS_VIEW',
  ASSETS_CREATE: 'ASSETS_CREATE',
  ASSETS_EDIT: 'ASSETS_EDIT',
  ASSETS_DELETE: 'ASSETS_DELETE',
  ASSETS_HANDOVER: 'ASSETS_HANDOVER',
  ASSETS_REPAIR_REPORT: 'ASSETS_REPAIR_REPORT',
  ASSETS_REPAIR_MANAGE: 'ASSETS_REPAIR_MANAGE',
  HANDOVERS_VIEW: 'HANDOVERS_VIEW',

  // Stock
  STOCK_VIEW: 'STOCK_VIEW',
  STOCK_MANAGE: 'STOCK_MANAGE',

  // Customer Management
  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_CREATE: 'CUSTOMERS_CREATE',
  CUSTOMERS_EDIT: 'CUSTOMERS_EDIT',
  CUSTOMERS_DELETE: 'CUSTOMERS_DELETE',

  // User & Division Management
  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',
  DIVISIONS_MANAGE: 'DIVISIONS_MANAGE',

  // Projects
  PROJECTS_VIEW: 'PROJECTS_VIEW',
  PROJECTS_CREATE: 'PROJECTS_CREATE',
  PROJECTS_EDIT: 'PROJECTS_EDIT',
  PROJECTS_APPROVE: 'PROJECTS_APPROVE',
  PROJECTS_MANAGE_TASKS: 'PROJECTS_MANAGE_TASKS',
  PROJECTS_MANAGE_TEAM: 'PROJECTS_MANAGE_TEAM',

  // Returns
  RETURNS_VIEW: 'RETURNS_VIEW',
  RETURNS_CREATE: 'RETURNS_CREATE',
  RETURNS_APPROVE: 'RETURNS_APPROVE',

  // Repairs
  REPAIRS_VIEW: 'REPAIRS_VIEW',
  REPAIRS_APPROVE: 'REPAIRS_APPROVE',

  // Imports
  DATA_IMPORT: 'DATA_IMPORT',

  // Purchases & Depreciation
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_CREATE: 'PURCHASES_CREATE',
  PURCHASES_EDIT: 'PURCHASES_EDIT',
  PURCHASES_DELETE: 'PURCHASES_DELETE',
  DEPRECIATION_VIEW: 'DEPRECIATION_VIEW',
  DEPRECIATION_CREATE: 'DEPRECIATION_CREATE',
  DEPRECIATION_EDIT: 'DEPRECIATION_EDIT',
  DEPRECIATION_DELETE: 'DEPRECIATION_DELETE',
} as const;
